#!/bin/bash

# Quick setup script to initialize Firestore data via Firebase Console

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║           MANUAL DATA INITIALIZATION (2 minutes)                  ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

open "https://console.firebase.google.com/project/simulation-project-74fda/firestore/data"

echo "In the Firestore console that just opened:"
echo ""
echo "1. Click '+ Start collection'"
echo "   Collection ID: market_state"
echo "   Document ID: current"
echo "   Add these fields:"
echo "     • currentPrice (number): 100"
echo "     • volume (number): 0"
echo "     • volatility (number): 0.02"
echo "     • newsImpact (number): 0"
echo "     • isActive (boolean): false"
echo "     • lastUpdated (timestamp): (click 'Use current time')"
echo ""
echo "2. Click '+ Start collection' again"
echo "   Collection ID: users"
echo "   Document ID: (auto-generated)"
echo "   Add these fields:"
echo "     • id (string): (copy the auto-generated ID)"
echo "     • role (string): trader"
echo "     • cash (number): 10000"
echo "     • portfolio (map): {}"
echo "     • totalValue (number): 10000"
echo "     • hasControl (boolean): false"
echo "     • joinedAt (timestamp): (click 'Use current time')"
echo ""
echo "3. Click '+ Start collection' again"
echo "   Collection ID: sessions"
echo "   Document ID: session_1"
echo "   Add these fields:"
echo "     • id (string): session_1"
echo "     • isActive (boolean): false"
echo "     • adminId (string): (leave empty)"
echo "     • participantCount (number): 0"
echo "     • startTime (timestamp): (click 'Use current time')"
echo ""
echo "After adding this data, your site will work!"
echo ""
echo "════════════════════════════════════════════════════════════════════"
echo "Your site: https://simulation-project-74fda.web.app"
echo "════════════════════════════════════════════════════════════════════"
